services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: freecord-postgres
    environment:
      POSTGRES_DB: freecord
      POSTGRES_USER: freecord_user
      POSTGRES_PASSWORD: freecord_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U freecord_user -d freecord"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - freecord-network

  # Redis for session storage and caching (optional but recommended)
  redis:
    image: redis:7-alpine
    container_name: freecord-redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - freecord-network

  # LiveKit Server (using built-in environment variables)
  livekit:
    image: livekit/livekit-server:latest
    container_name: freecord-livekit
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    ports:
      - "7880:7880"    # HTTP API
      - "7881:7881"    # RTC TCP
      - "50000-50100:50000-50100/udp" # RTC UDP
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
    environment:
      # LiveKit built-in environment variable for API keys
      LIVEKIT_KEYS: "${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}"
    networks:
      - freecord-network

  # Freecord Application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        NEXT_PUBLIC_CLERK_SIGN_IN_URL: /sign-in
        NEXT_PUBLIC_CLERK_SIGN_UP_URL: /sign-up
        NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: /
        NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: /
        NEXT_PUBLIC_LIVEKIT_URL: ${NEXT_PUBLIC_LIVEKIT_URL}
    container_name: freecord-app
    env_file:
      - .env
    environment:
      # Database
      DATABASE_URL: ${DATABASE_URL:-postgresql://freecord_user:freecord_password@postgres:5432/freecord}
      
      # Node Environment
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      
      # Clerk Authentication (runtime)
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: /sign-in
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: /sign-up
      NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: /
      NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: /

      # LiveKit
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
      NEXT_PUBLIC_LIVEKIT_URL: ${NEXT_PUBLIC_LIVEKIT_URL}
      
      # Optional Redis URL
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      livekit:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - freecord-network
    volumes:
      # Mount uploads directory for persistent file storage
      - uploads_data:/app/uploads

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  uploads_data:
    driver: local

networks:
  freecord-network:
    driver: bridge

