#!/usr/bin/env bash
set -euo pipefail

# Run Freecord in DEV mode using docker-compose.dev.yml

cd "$(dirname "$0")"

if ! command -v docker >/dev/null 2>&1; then
  echo "Docker is required but not installed. Please install Docker." >&2
  exit 1
fi

# Choose docker compose command
compose_cmd="docker compose"
if ! docker compose version >/dev/null 2>&1; then
  if command::=docker-compose && command -v docker-compose >/dev/null 2>&1; then
    compose_cmd="docker-compose"
  else
    echo "Docker Compose is required. Install docker compose plugin or docker-compose." >&2
    exit 1
  fi
fi

# Ensure dev env file exists
if [ ! -f .env.dev ]; then
  echo "Creating .env.dev with defaults for dev.miyov.io"
  cat > .env.dev <<'EOF'
# Generated by run-dev.sh
DEV_NEXT_PUBLIC_APP_URL=https://dev.miyov.io

# Database
DEV_DATABASE_URL=postgresql://freecord_user:freecord_password@postgres:5432/freecord_dev

# Clerk (fill with your dev project keys)
DEV_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
DEV_CLERK_SECRET_KEY=

# LiveKit (dev)
DEV_LIVEKIT_API_KEY=
DEV_LIVEKIT_API_SECRET=
DEV_NEXT_PUBLIC_LIVEKIT_URL=wss://livekit.dev.miyov.io

# Redis
DEV_REDIS_URL=redis://redis:6379

# Flags
ENABLE_DEVELOPMENT_FEATURES=true
EOF
  echo "Created .env.dev. Review and fill missing values if needed."
fi

echo "Starting Freecord DEV stack (docker-compose.dev.yml) ..."
$compose_cmd -f docker-compose.dev.yml up -d --build

echo "DEV stack is up. Useful endpoints:"
echo "- App:            http://localhost:3001 (or https://dev.miyov.io via your DNS/proxy)"
echo "- LiveKit API:    http://localhost:17880 (external)"
echo "- Postgres:       localhost:55432"
echo "- Redis:          localhost:26379"

echo "View logs: $compose_cmd logs -f"

